=== BenjiTayokosenGit/Library/Books/Book.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
<xs:element name="book">
  <xs:complexType>
   <xs:sequence> 
     <xs:element name="title"  type="xs:string"/>
     <xs:element name="title_keywords">
        <xs:complexType>
          <xs:sequence>
             <xs:element name="key" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
     </xs:element>
     <xs:element name="writer"  type="xs:string"/>
     <xs:element name="writer_keywords">
        <xs:complexType>
           <xs:sequence>
              <xs:element name="key" minOccurs="1" maxOccurs="unbounded"/>
           </xs:sequence>
        </xs:complexType>
     </xs:element>
     <xs:element name="about_the_Book"  type="xs:string"/>
     <xs:element name="picture">
       <xs:complexType>
          <xs:sequence>
            <xs:element name="url"  type="xs:string"/>
            <xs:element name="description"  type="xs:string"/>
          </xs:sequence>
       </xs:complexType>
     </xs:element>
     <xs:element name="pages">
       <xs:complexType>
         <xs:sequence>
          <xs:element name="number" type="xs:decimal"/>
          <xs:element name="page" minOccurs="0" maxOccurs="unbounded">
             <xs:complexType>
               <xs:sequence>
                 <xs:element name="content">
                    <xs:complexType>
                      <xs:sequence>
                       <xs:element name="paragraph" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                      </xs:sequence>
                    </xs:complexType>
                 </xs:element>
               </xs:sequence>
             </xs:complexType>
          </xs:element>
         </xs:sequence>
       </xs:complexType>
     </xs:element>
     <xs:element name="comment" type="xs:string"/>
     <xs:element name="evaluation" type="xs:decimal"/>
   </xs:sequence> 
  </xs:complexType>
</xs:element>
</xs:schema>

=== BenjiTayokosenGit/Library/Books/Book1.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="book.xsl"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Book.xsd">
 <title>The Story of An Hour</title>
 <title_keywords>
      <key>The Story of An Hour</key>
      <key>The Story of An</key>
      <key>The Story of</key>
      <key>The Story</key>
      <key>The</key>
      <key>Story</key>
      <key>Story of</key>
      <key>Story of an</key>
      <key>Story of an hour</key>
      <key>of an hour</key>
      <key>an hour</key>
      <key>hour</key>
 </title_keywords>
 <writer>Kate Chopin</writer>
 <writer_keywords>
      <key>Kate</key>
      <key>Kate chopin</key>
      <key>chopin</key>
      <key>chopin kate</key>
 </writer_keywords>
 <about_the_Book>This story was first published in 1894 as The Dream of an Hour before being republished under this title in 1895. We encourage students and teachers to use our The Story of An Hour Study Guide and Feminist Literature Study Guide.</about_the_Book>
 <picture>
    <url>Img/1.jpg</url>
    <description>Carl Halsoe, Waiting by the Window, 1863</description>
 </picture>
 <pages>
    <number>6</number>
    <page>
        <content>
           <paragraph>Knowing that Mrs. Mallard was afflicted with a heart trouble, great care was taken to break to her as gently as possible the news of her husband's death.</paragraph>             
           <paragraph>It was her sister Josephine who told her, in broken sentences; veiled hints that revealed in half concealing. Her husband's friend Richards was there, too, near her. It was he who had been in the newspaper office when intelligence of the railroad disaster was received, with Brently Mallard's name leading the list of "killed." He had only taken the time to assure himself of its truth by a second telegram, and had hastened to forestall any less careful, less tender friend in bearing the sad message.</paragraph>    
           <paragraph>She did not hear the story as many women have heard the same, with a paralyzed inability to accept its significance. She wept at once, with sudden, wild abandonment, in her sister's arms. When the storm of grief had spent itself she went away to her room alone. She would have no one follow her.</paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph>There stood, facing the open window, a comfortable, roomy armchair. Into this she sank, pressed down by a physical exhaustion that haunted her body and seemed to reach into her soul.</paragraph>
           <paragraph>She could see in the open square before her house the tops of trees that were all aquiver with the new spring life. The delicious breath of rain was in the air. In the street below a peddler was crying his wares. The notes of a distant song which someone was singing reached her faintly, and countless sparrows were twittering in the eaves.</paragraph>
           <paragraph>There were patches of blue sky showing here and there through the clouds that had met and piled one above the other in the west facing her window.</paragraph>
           <paragraph>She sat with her head thrown back upon the cushion of the chair, quite motionless, except when a sob came up into her throat and shook her, as a child who has cried itself to sleep </paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph>continues to sob in its dreams.</paragraph>
           <paragraph>She was young, with a fair, calm face, whose lines bespoke repression and even a certain strength. But now there was a dull stare in her eyes, whose gaze was fixed away off yonder on one of those patches of blue sky;</paragraph>
           <paragraph>It was not a glance of reflection, but rather indicated a suspension of intelligent thought.</paragraph>
           <paragraph>There was something coming to her and she was waiting for it, fearfully. What was it? She did not know; it was too subtle and elusive to name. But she felt it, creeping out of the sky, reaching toward her through the sounds, the scents, the color that filled the air.</paragraph>
           <paragraph>She did not stop to ask if it were or were not a monstrous joy that held her. A clear and exalted perception enabled her to dismiss the suggestion as trivial. She knew that she would weep again when she saw the kind, tender hands folded in death;</paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph> the face that had never looked save with love upon her, fixed and gray and dead. But she saw beyond that bitter moment a long procession of years to come that would belong to her absolutely.</paragraph>
           <paragraph> And she opened and spread her arms out to them in welcome. </paragraph>
           <paragraph>There would be no one to live for during those coming years; she would live for herself. There would be no powerful will bending hers in that blind persistence with which men and women believe they have a right to impose a private will upon a fellow-creature. A kind intention or a cruel intention made the act seem no less a crime as she looked upon it in that brief moment of illumination.</paragraph>
           <paragraph>And yet she had loved him--sometimes. Often she had not. What did it matter! What could love, the unsolved mystery, count for in the face of this possession of self-assertion which she suddenly recognized as the strongest </paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph>impulse of her being!."Free! Body and soul free!" she kept whispering.</paragraph>
           <paragraph>Josephine was kneeling before the closed door with her lips to the keyhole, imploring for admission. "Louise, open the door! I beg; open the door--you will make yourself ill. What are you doing, Louise? For heaven's sake open the door.</paragraph>
           <paragraph>"Go away. I am not making myself ill." No; she was drinking in a very elixir of life through that open window.</paragraph>
           <paragraph>Her fancy was running riot along those days ahead of her. Spring days, and summer days, and all sorts of days that would be her own. She breathed a quick prayer that life might be long. It was only yesterday she had thought with a shudder that life might be long.</paragraph>
           <paragraph>She arose at length and opened the door to her sister's importunities. There was a feverish triumph in her eyes, and she carried herself </paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph>unwittingly like a goddess of Victory. She clasped her sister's waist, and together they descended the stairs. Richards stood waiting for them at the bottom.</paragraph>
           <paragraph>Someone was opening the front door with a latchkey. It was Brently Mallard who entered, a little travel-stained, composedly carrying his grip-sack and umbrella. He had been far from the scene of the accident, and did not even know there had been one. He stood amazed at Josephine's piercing cry; at Richards' quick motion to screen him from the view of his wife.</paragraph>
           <paragraph>When the doctors came they said she had died of heart disease--of the joy that kills.</paragraph>
        </content>
    </page>
 </pages>
 <comment>Earlier, I pointed out that this story was first published in 1894 as The Dream of an Hour before being republished in 1895 as The Story of an Hour. Having read the story, why do you suppose Kate Chopin chose to change that one word? Given societal norms and expecations about women and marriage in 1895, do you see how simply changing a single word in the title may have been an answer to the controversy and criticism that the story engendered at that time?</comment>
 <evaluation>7</evaluation>
</book>

=== BenjiTayokosenGit/Library/Books/Book2.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="book.xsl"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Book.xsd">
 <title>How the Camel Got His Hump</title>
 <title_keywords>
    <key>How the camel</key>
    <key>How the camel got</key>
    <key>How the camel got his</key>
    <key>How the camel got his hump</key>
    <key>the camel</key>
    <key>the camel got</key>
    <key>the camel got his</key>
    <key>the camel got his hump</key>
    <key>camel</key>
    <key>camel got</key>
    <key>camel got his</key>
    <key>camel got his hump</key>
    <key>got his hump</key>
    <key>his hump</key>
    <key>hump</key>
 </title_keywords>
 <writer>Rudyard Kipling</writer>
 <writer_keywords>
    <key>Rudyard</key>
    <key>Rudyard Kipling</key>
    <key>Kipling</key>
    <key>Kipling Rudyard</key>
 </writer_keywords>
 <about_the_Book>Rudyard Kipling's Just So Stories (1902) offer young readers the opportunity to identify literary devices like anthropomorphism and explore the characteristics of what makes a "tall tale" believable.</about_the_Book>
 <picture>
    <url>Img/2.jpg</url>
    <description></description>
 </picture>
 <pages>
    <number>8</number>
    <page>
        <content>
           <paragraph>NOW this is the next tale, and it tells how the Camel got his big hump.</paragraph>             
           <paragraph>In the beginning of years, when the world was so new and all, and the Animals were just beginning to work for Man, there was a Camel, and he lived in the middle of a Howling Desert because he did not want to work; and besides, he was a Howler himself. So he ate sticks and thorns and tamarisks and milkweed and prickles, most 'scruciating idle; and when anybody spoke to him he said 'Humph!' Just 'Humph!' and no more.</paragraph>    
           <paragraph>Presently the Horse came to him on Monday morning, with a saddle on his back and a bit in his mouth, and said, 'Camel, O Camel, come out and trot like the rest of us.'</paragraph>
           <paragraph>'Humph!' said the Camel; and the Horse went away and told the Man.</paragraph>
           <paragraph>Presently the Dog came to him, with a stick in his mouth, and said, 'Camel, O Camel, </paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph>come and fetch and carry like the rest of us.'</paragraph>
           <paragraph>'Humph!' said the Camel; and the Dog went away and told the Man.</paragraph>
           <paragraph>Presently the Ox came to him, with the yoke on his neck and said, 'Camel, O Camel, come and plough like the rest of us.'</paragraph>
           <paragraph>'Humph!' said the Camel; and the Ox went away and told the Man.</paragraph>
           <paragraph>At the end of the day the Man called the Horse and the Dog and the Ox together, and said, 'Three, O Three, I'm very sorry for you (with the world so new-and-all); but that Humph-thing in the Desert can't work, or he would have been here by now, so I am going to leave him alone, and you must work double-time to make up for it.'That made the Three very angry (with the world so new-and-all), and they held a palaver, and an indaba, and a punchayet, and a pow-wow on the edge of the Desert; and the Camel came chewing on milkweed most </paragraph>
           <paragraph></paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph>'scruciating idle, and laughed at them. Then he said 'Humph!' and went away again.</paragraph>
           <paragraph>Presently there came along the Djinn in charge of All Deserts, rolling in a cloud of dust (Djinns always travel that way because it is Magic), and he stopped to palaver and pow-pow with the Three.</paragraph>
           <paragraph>'Djinn of All Deserts,' said the Horse, 'is it right for any one to be idle, with the world so new-and-all?'</paragraph>
           <paragraph>'Certainly not,' said the Djinn.</paragraph>
           <paragraph>Well,' said the Horse, 'there's a thing in the middle of your Howling Desert (and he's a Howler himself) with a long neck and long legs, and he hasn't done a stroke of work since Monday morning. He won't trot.'</paragraph>
           <paragraph>'Whew!' said the Djinn, whistling, 'that's my Camel, for all the gold in Arabia! What does he say about it?'</paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph>'He says "Humph!"' said the Dog;'and he won't fetch and carry.'</paragraph>
           <paragraph>'Does he say anything else?'</paragraph>
           <paragraph>'Only "Humph!"; and he won't plough,' said the Ox.</paragraph>
           <paragraph>'Very good,' said the Djinn. 'I'll humph him if you will kindly wait a minute.'</paragraph>
           <paragraph>The Djinn rolled himself up in his dust-cloak, and took a bearing across the desert, and found the Camel most 'scruciatingly idle, looking at his own reflection in a pool of water.</paragraph>
           <paragraph>'My long and bubbling friend,' said the Djinn, 'what's this I hear of your doing no work, with the world so new-and-all?'</paragraph>
           <paragraph>'Humph!' said the Camel.</paragraph>
           <paragraph>The Djinn sat down, with his chin in his hand, and began to think a Great Magic, </paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph>while the Camel looked at his own reflection in the pool of water.</paragraph>
           <paragraph>'You've given the Three extra work ever since Monday morning, all on account of your 'scruciating idleness,' said the Djinn; and he went on thinking Magics, with his chin in his hand.</paragraph>
           <paragraph>'Humph!' said the Camel.</paragraph>
           <paragraph>'I shouldn't say that again if I were you,' said the Djinn; you might say it once too often. Bubbles, I want you to work.'</paragraph>
           <paragraph>And the Camel said 'Humph!' again; but no sooner had he said it than he saw his back, that he was so proud of, puffing up and puffing up into a great big lolloping humph.</paragraph>
           <paragraph>'Do you see that?' said the Djinn. 'That's your very own humph that you've brought upon your very own self by not working. To-day is Thursday, and you've done no work since </paragraph>
        </content>
    </page>
    <page>
        <content>
            <paragraph>Monday, when the work began. Now you are going to work.'</paragraph>
            <paragraph>'How can I,' said the Camel, 'with this humph on my back?'</paragraph>
            <paragraph>'That's made a-purpose,' said the Djinn, 'all because you missed those three days. You will be able to work now for three days without eating, because you can live on your humph; and don't you ever say I never did anything for you. Come out of the Desert and go to the Three, and behave. Humph yourself!'</paragraph>
            <paragraph>And the Camel humphed himself, humph and all, and went away to join the Three. And from that day to this the Camel always wears a humph (we call it 'hump' now, not to hurt his feelings); but he has never yet caught up with the three days that he missed at the beginning of the world, and he has never yet learned how to behave.</paragraph>
            <paragraph>THE Camel's hump is an ugly lump  Which </paragraph>
        </content>
    </page>
    <page>
        <content>
           <paragraph>well you may see at the Zoo;But uglier yet is the hump we get From having too little to do.Kiddies and grown-ups too-oo-oo, If we haven't enough to do-oo-oo, We get the hump-- Cameelious hump-- The hump that is black and blue!</paragraph>
           <paragraph>We climb out of bed with a frouzly head And a snarly-yarly voice. We shiver and scowl and we grunt and we growl At our bath and our boots and our toys;</paragraph>
           <paragraph>And there ought to be a corner for me (And I know there is one for you) When we get the hump-- Cameelious hump-- The hump that is black and blue!</paragraph>
           <paragraph>The cure for this ill is not to sit still, Or frowst with a book by the fire; But to take a large hoe and a shovel also, And dig till you gently perspire;</paragraph>
           <paragraph>And then you will find that the sun and the wind.</paragraph>
        </content>
    </page>
    <page>
         <content>
           <paragraph> And the Djinn of the Garden too, Have lifted the hump-- The horrible hump-- The hump that is black and blue!</paragraph>
           <paragraph>I get it as well as you-oo-oo-- If I haven't enough to do-oo-oo-- We all get hump-- Cameelious hump-- Kiddies and grown-ups too!</paragraph>            
         </content>  
    </page>
 </pages>
 <comment>Enjoy Kipling's How the Leopard Got His Spots. Many of Kipling's Just So Stories are often read in grades 2-3.</comment>
 <evaluation>8</evaluation>
</book>

=== BenjiTayokosenGit/Library/Books/Book0.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="book.xsl"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Book.xsd">
 <title>Cousin Tribulation's Story</title>
 <title_keywords>
     <key>Cousin Tribulation's Story</key>
     <key>Cousin Tribulation's</key>
     <key>Cousin Tribulation</key>
     <key>Cousin</key>
     <key>Tribulation's Story</key>
     <key>Tribulation Story</key>
     <key>Tribulation</key>
     <key>Story</key>
 </title_keywords>
 <writer>Louisa May Alcott</writer>
 <writer_keywords>
    <key>Louisa</key>
    <key>Louisa may</key>
    <key>Louisa alcott</key>
    <key>louisa may alcott</key>
    <key>louisa alcott may</key>
    <key>may</key>
    <key>may alcott</key>
    <key>may louisa</key>
    <key>may alcott louisa</key>
    <key>may louisa alcott</key>
    <key>alcott</key>
    <key>alcott may</key>
    <key>alcott louisa</key>
    <key>alcott may louisa</key>
    <key>alcott louisa may</key>
 </writer_keywords>
 <about_the_Book>Cousin Tribulation's Story was featured as The Short Story of the Day on Thu, Dec 28, 2017</about_the_Book>
 <picture>
    <url>Img/0.jpg</url>
    <description></description>
 </picture>
 <pages>
    <number>6</number>
    <page>
       <content>
          <paragraph>Dear Merrys:--As a subject appropriate to the season, I want to tell you about a New Year's breakfast which I had when I was a little girl. What do you think it was? A slice of dry bread and an apple. This is how it happened, and it is a true story, every word.</paragraph>
          <paragraph>As we came down to breakfast that morning, with very shiny faces and spandy clean aprons, we found father alone in the dining-room.</paragraph>
          <paragraph>"Happy New Year, papa! Where is mother?" we cried.</paragraph>
          <paragraph>"A little boy came begging and said they were starving at home, so your mother went to see and--ah, here she is."</paragraph>
          <paragraph>As papa spoke, in came mamma, looking very cold, rather sad, and very much excited.</paragraph> 
          <paragraph>"Children, don't begin till you hear what I have to say," she cried; and we sat staring at her, with the breakfast untouched before us.</paragraph>         
       </content>
    </page>
    <page>
       <content>
          <paragraph>"Children, don't begin till you hear what I have to say," she cried; and we sat staring at her, with the breakfast untouched before us.</paragraph>
          <paragraph>"Not far away from here, lies a poor woman with a little new-born baby. Six children are huddled into one bed to keep from freezing, for they have no fire. There is nothing to eat over there; and the oldest boy came here to tell me they were starving this bitter cold day. My little girls, will you give them your breakfast, as a New Year's gift?"</paragraph>
          <paragraph>We sat silent a minute, and looked at the nice, hot porridge, creamy milk, and good bread and butter; for we were brought up like English children, and never drank tea or coffee, or ate anything but porridge for our breakfast.</paragraph>
          <paragraph>"I wish we'd eaten it up," thought I, for I was rather a selfish child, and very hungry</paragraph>
          <paragraph>"I'm so glad you come before we began," said Nan, cheerfully.</paragraph>         
       </content>
    </page>
    <page>
       <content>
          <paragraph>"May I go and help carry it to the poor, little children?" asked Beth, who had the tenderest heart that ever beat under a pinafore.</paragraph>
          <paragraph>"I can carry the lassy pot," said little May, proudly giving the thing she loved best.</paragraph>
          <paragraph>"And I shall take all the porridge," I burst in, heartily ashamed of my first feeling.</paragraph>
          <paragraph>"You shall put on your things and help me, and when we come back, we'll get something to eat," said mother, beginning to pile the bread and butter into a big basket.</paragraph>
          <paragraph>We were soon ready, and the procession set out. First, papa, with a basket of wood on one arm and coal on the other; mamma next, with a bundle of warm things and the teapot; Nan and I carried a pail of hot porridge between us, and each a pitcher of milk; Beth brought some cold meat, May the "lassy pot," and her old hood and boots; and Betsey, the girl, brought up the rear with a bag of potatoes and some meal.</paragraph>          
         </content>
    </page>
    <page>
       <content>
         <paragraph>Fortunately it was early, and we went along back streets, so few people saw us, and no one laughed at the funny party.</paragraph>
         <paragraph>What a poor, bare, miserable place it was, to be sure,--broken windows, no fire, ragged clothes, wailing baby, sick mother, and a pile of pale, hungry children cuddled under one quilt, trying to keep warm. How the big eyes stared and the blue lips smiled as we came in!</paragraph>
         <paragraph>"Ah, mein Gott! it is the good angels that come to us!" cried the poor woman, with tears of joy.</paragraph>
         <paragraph>"Funny angels, in woollen hoods and red mittens," said I; and they all laughed.</paragraph>
         <paragraph>Then we fell to work, and in fifteen minutes, it really did seem as if fairies had been at work there. Papa made a splendid fire in the old fireplace and stopped up the broken window with his own hat and coat. Mamma set the shivering children round the fire, and wrapped the poor woman in warm things. Betsey and </paragraph>
        </content>
    </page>
    <page>
       <content>
          <paragraph>the rest of us spread the table, and fed the starving little ones.</paragraph>
          <paragraph>"Das ist gute!" "Oh, nice!" "Der angel--Kinder!" cried the poor things as they ate and smiled and basked in the warm blaze. We had never been called "angel-children" before, and we thought it very charming, especially I who had often been told I was "a regular Sancho." What fun it was! Papa, with a towel for an apron, fed the smallest child; mamma dressed the poor little new-born baby as tenderly as if it had been her own. Betsey gave the mother gruel and tea, and comforted her with assurance of better days for all. Nan, Lu, Beth, and May flew about among the seven children, talking and laughing and trying to understand their funny, broken English. It was a very happy breakfast, though we didn't get any of it;</paragraph>
          <paragraph> and when we came away, leaving them all so comfortable, and promising to bring clothes and food by and by, I think there were not in all the hungry little girls who gave away their </paragraph>          
       </content>
    </page> 
    <page>
        <content>
           <paragraph>breakfast, and contented themselves with a bit of bread and an apple of New Year's day.</paragraph>
        </content>
    </page>   
 </pages>
 <comment>This story is featured in our collection of "feel-good" 75 Short Short Stories to read when you have five minutes to spare, Christmas Stories, and Foodie Stories.</comment>
 <evaluation>8</evaluation>
</book>
